export const SHOW_USER_EDIT = "SHOW_USER_EDIT";
export const CLOSE_USER_EDIT = "CLOSE_USER_EDIT";

export const SHOW_DELETE_CONFIRM = "SHOW_DELETE_CONFIRM";
export const CLOSE_DELETE_CONFIRM = "CLOSE_DELETE_CONFIRM";

export const SHOW_ADD_NEW_USER = "SHOW_ADD_NEW_USER";
export const CLOSE_ADD_NEW_USER = "HIDE_ADD_NEW_USER";

export const SHOW_PROJECT_MODAL = "SHOW_PROJECT_MODAL";
export const HIDE_PROJECT_MODAL = "HIDE_PROJECT_MODAL";

export const SHOW_EDIT_PROJECT = "SHOW_EDIT_PROJECT";
export const HIDE_EDIT_PROJECT = "HIDE_EDIT_PROJECT";

export const SHOW_TICKET_MODAL = "SHOW_TICKET_MODAL";
export const HIDE_TICKET_MODAL = "HIDE_TICKET_MODAL";

export const SHOW_TICKET_MODAL_EDIT = "SHOW_TICKET_MODAL";
export const HIDE_TICKET_MODAL_EDIT = "HIDE_TICKET_MODAL";
