export const FETCH_SINGLE_PROJECT_REQUEST = "FETCH_SINGLE_PROJECT_REQUEST";
export const FETCH_SINGLE_PROJECT_SUCCESS = "FETCH_SINGLE_PROJECT_SUCCESS";
export const FETCH_SINGLE_PROJECT_FAILURE = "FETCH_SINGLE_PROJECT_FAILURE";
