/* export const DISPATCH_PROJECT_TO_STATE = "DISPATCH_PROJECT_TO_STATE";
export const DISPATCH_PROJECT_TO_STATE_SUCCESS =
  " DISPATCH_PROJECT_TO_STATE_SUCCESS";
export const DISPATCH_PROJECT_TO_STATE_FAILURE =
  " DISPATCH_PROJECT_TO_STATE_FAILURE";
 */
