export const FETCH_PROJECT = "FETCH_PROJECT";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILURE = "FETCH_PROJECT_FAILURE";

export const DISPATCH_PROJECT_TO_STATE = "DISPATCH_PROJECT_TO_STATE";
export const DISPATCH_PROJECT_TO_STATE_SUCCESS =
  " DISPATCH_PROJECT_TO_STATE_SUCCESS";
export const DISPATCH_PROJECT_TO_STATE_FAILURE =
  " DISPATCH_PROJECT_TO_STATE_FAILURE";
